### ISSUE TITLE
Retain Capitlization for config conversions

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoConf#26]
Certain configs are losing capitlization, for example `notation.yaml` goes to lower case but includes class names:

```
[superscript]
ModelComponent0=M0
ModelComponent1=M1
Gaussian=g
Exponential=e
```

```
  superscript:
    exponential: e
    gaussian: g
    modelcomponent0: M0
    modelcomponent1: M1
```
